### ISSUE TITLE
Overriding the views

### ISSUE THREAD

**Issue by williammgy** [kricha/DoctrineAuditBundle#11]
Hi,

Hope you're doing well lately.

First of all I'd like to thank you for your work and this great bundle.

I've recently downloaded it in a 4.4 project and I would like to modify a few things regarding the 'view' part of the bundle. Basically it's about replacing the endpoints (.i.e */table-name* instead of */App-Entity-TableName*), getting rid of all the `App:` parts throughout the templates and deactivating or deleting the route with the details part.

I'm not sure how to do this properly, would you give me some hints on how I could manage to do so?

Thank you very much in advance for your consideration.

Regards,
William.

**Comment by kricha** [comment]
@williammgy hello,
could you show me examples of the problem?

thanks

**Comment by williammgy** [comment]
Nevermind, I found the solution.

Thanks for your answer though!

Regards,
William.
